package sn.senannonces.annonceservice.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * JPA entity that represents a classified ad on the SenAnnonces platform.
 *
 * <p>An ad is created with the {@link AnnonceStatus#EN_ATTENTE} status and
 * progresses through the lifecycle defined in {@link AnnonceStatus}.
 */
@Entity
@Table(name = "annonces")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Annonce {

    /** Unique identifier of the ad, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short title displayed in listings. */
    @Column(nullable = false, length = 200)
    private String titre;

    /** Free-text description of the item or service being advertised. */
    @Column(nullable = false, length = 2000)
    private String description;

    /** Asking price expressed in XOF (CFA franc). */
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal prix;

    /** City where the item is located. */
    @Column(nullable = false, length = 100)
    private String ville;

    /** Current lifecycle status. Persisted as a string for forward compatibility. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AnnonceStatus statut;
}
